# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/qt_designer/new_polygon_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newPolygonWindow(object):
    def setupUi(self, newPolygonWindow):
        newPolygonWindow.setObjectName("newPolygonWindow")
        newPolygonWindow.setEnabled(True)
        newPolygonWindow.resize(370, 229)
        self.centralwidget = QtWidgets.QWidget(newPolygonWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.setPointsLabel = QtWidgets.QLabel(self.centralwidget)
        self.setPointsLabel.setGeometry(QtCore.QRect(10, 10, 81, 18))
        self.setPointsLabel.setObjectName("setPointsLabel")
        self.newXLabel = QtWidgets.QLabel(self.centralwidget)
        self.newXLabel.setGeometry(QtCore.QRect(30, 40, 21, 18))
        self.newXLabel.setObjectName("newXLabel")
        self.newYLabel = QtWidgets.QLabel(self.centralwidget)
        self.newYLabel.setGeometry(QtCore.QRect(30, 70, 16, 16))
        self.newYLabel.setObjectName("newYLabel")
        self.newXTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.newXTextEdit.setGeometry(QtCore.QRect(50, 30, 51, 31))
        self.newXTextEdit.setObjectName("newXTextEdit")
        self.newTTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.newTTextEdit.setGeometry(QtCore.QRect(50, 60, 51, 31))
        self.newTTextEdit.setObjectName("newTTextEdit")
        self.addNewPointPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addNewPointPushButton.setGeometry(QtCore.QRect(50, 90, 51, 34))
        self.addNewPointPushButton.setObjectName("addNewPointPushButton")
        self.newPointsTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.newPointsTextBrowser.setGeometry(QtCore.QRect(160, 0, 181, 131))
        self.newPointsTextBrowser.setObjectName("newPointsTextBrowser")
        self.drawPolygonPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.drawPolygonPushButton.setGeometry(QtCore.QRect(250, 140, 88, 34))
        self.drawPolygonPushButton.setObjectName("drawPolygonPushButton")
        newPolygonWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(newPolygonWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 30))
        self.menubar.setObjectName("menubar")
        newPolygonWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(newPolygonWindow)
        self.statusbar.setObjectName("statusbar")
        newPolygonWindow.setStatusBar(self.statusbar)

        self.retranslateUi(newPolygonWindow)
        QtCore.QMetaObject.connectSlotsByName(newPolygonWindow)

    def retranslateUi(self, newPolygonWindow):
        _translate = QtCore.QCoreApplication.translate
        newPolygonWindow.setWindowTitle(_translate("newPolygonWindow", "MainWindow"))
        self.setPointsLabel.setText(_translate("newPolygonWindow", "Set points:"))
        self.newXLabel.setText(_translate("newPolygonWindow", "X:"))
        self.newYLabel.setText(_translate("newPolygonWindow", "Y:"))
        self.addNewPointPushButton.setText(_translate("newPolygonWindow", "Add "))
        self.drawPolygonPushButton.setText(_translate("newPolygonWindow", "Draw"))
